# Generated by Django 4.2.24 on 2026-08-08 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_payload', models.JSONField(blank=True, default=dict)),
                ('submission_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_data', to='submissions.submissionversion')),
            ],
        ),
    ]
