# Generated by Django 4.2.24 on 2026-08-08 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('reference_year', models.PositiveIntegerField()),
                ('reference_month', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=16)),
                ('is_demo', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='core.institution')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_periods', to='core.unit')),
            ],
            options={
                'ordering': ('-reference_year', '-reference_month'),
                'unique_together': {('unit', 'reference_year', 'reference_month')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_status', models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('synced', 'Sincronizado'), ('conflict', 'Conflito'), ('returned', 'Devolvido')], default='draft', max_length=16)),
                ('client_submission_uuid', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.institution')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.reportingperiod')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.unit')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('client_version_uuid', models.UUIDField(unique=True)),
                ('payload', models.JSONField()),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Aguardando sincronização'), ('synced', 'Sincronizado'), ('error', 'Erro de sincronização'), ('conflict', 'Conflito'), ('returned', 'Devolvido para correção')], default='queued', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_versions', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='submissions.submission')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('submission', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'login'), ('logout', 'logout'), ('draft_saved', 'draft_saved'), ('submission_closed', 'submission_closed'), ('sync_started', 'sync_started'), ('sync_completed', 'sync_completed'), ('sync_failed', 'sync_failed'), ('conflict_detected', 'conflict_detected')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='submissions.submission')),
                ('submission_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='submissions.submissionversion')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
