# Generated by Django 4.2.24 on 2026-08-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CollectionVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('operational_definition', models.TextField()),
                ('variable_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal'), ('text', 'Text'), ('select', 'Select'), ('boolean', 'Boolean')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_source', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('select_options', models.JSONField(blank=True, default=list)),
                ('is_demo', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='submissions.collectionmodule')),
            ],
            options={
                'ordering': ('module__display_order', 'display_order', 'name'),
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='current_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('submitted', 'Submetido'), ('synced', 'Sincronizado'), ('conflict', 'Conflito'), ('returned', 'Devolvido'), ('accepted', 'Aceito'), ('consolidated', 'Consolidado')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='submissionversion',
            name='status',
            field=models.CharField(choices=[('queued', 'Aguardando sincronização'), ('synced', 'Sincronizado'), ('error', 'Erro de sincronização'), ('conflict', 'Conflito'), ('returned', 'Devolvido para correção'), ('received', 'Recebido'), ('accepted', 'Aceito'), ('consolidated', 'Consolidado')], default='queued', max_length=16),
        ),
        migrations.CreateModel(
            name='IndicatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('dimension', models.CharField(choices=[('structure', 'Estrutura'), ('process', 'Processo'), ('result', 'Resultado')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('formula_kind', models.CharField(choices=[('ratio_percentage', 'Razão percentual')], max_length=32)),
                ('formula_label', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('interpretation', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('denominator_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_denominator_in', to='submissions.collectionvariable')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='submissions.collectionmodule')),
                ('numerator_variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_numerator_in', to='submissions.collectionvariable')),
            ],
            options={
                'ordering': ('module__display_order', 'name'),
                'unique_together': {('code', 'version')},
            },
        ),
    ]
