import type { BootstrapPayload, CollectionVariableDefinition, IndicatorDefinition } from "../types/submission";

const variable = (
  id: number,
  code: string,
  name: string,
  module: number,
  moduleCode: string,
  unit: string,
  required: boolean,
  displayOrder: number,
  helpText: string,
  overrides: Partial<CollectionVariableDefinition> = {},
): CollectionVariableDefinition => ({
  id,
  code,
  name,
  operational_definition: `${name} agregado no período de referência.`,
  module,
  module_code: moduleCode,
  variable_type: "integer",
  unit,
  required,
  min_value: 0,
  max_value: null,
  expected_source: "Registro institucional agregado da unidade.",
  help_text: helpText,
  display_order: displayOrder,
  active: true,
  version: 1,
  select_options: [],
  is_demo: true,
  status: required ? "demonstrativo" : "candidato",
  ...overrides,
});

const indicator = (
  id: number,
  code: string,
  name: string,
  module: number,
  moduleCode: string,
  formulaKind: IndicatorDefinition["formula_kind"],
  formulaLabel: string,
  numeratorVariable: number,
  numeratorVariableCode: string,
  denominatorVariable: number,
  denominatorVariableCode: string,
): IndicatorDefinition => ({
  id,
  code,
  name,
  definition: `${name} calculado automaticamente a partir dos dados-base agregados.`,
  module,
  module_code: moduleCode,
  dimension: "result",
  unit: "%",
  formula_kind: formulaKind,
  formula_label: formulaLabel,
  numerator_variable: numeratorVariable,
  numerator_variable_code: numeratorVariableCode,
  denominator_variable: denominatorVariable,
  denominator_variable_code: denominatorVariableCode,
  version: 1,
  valid_from: "2026-08-11",
  valid_to: null,
  interpretation: "Leitura demonstrativa para o dashboard MVP.",
  is_demo: true,
  status: "demonstrativo",
});

export const demoBootstrap: BootstrapPayload = {
  institution: { id: 1, name: "Instituição Demonstrativa HEMO-ANGOLA" },
  unit: { id: 1, name: "Unidade Demonstrativa", code: "DEMO-UNIT-01" },
  reportingPeriod: {
    id: 8,
    label: "Agosto/2026",
    reference_year: 2026,
    reference_month: 8,
    start_date: "2026-08-01",
    end_date: "2026-08-31",
    status: "open",
  },
  reportingPeriods: [
    { id: 12, label: "Dezembro/2026", reference_year: 2026, reference_month: 12, start_date: "2026-12-01", end_date: "2026-12-31", status: "open" },
    { id: 11, label: "Novembro/2026", reference_year: 2026, reference_month: 11, start_date: "2026-11-01", end_date: "2026-11-30", status: "open" },
    { id: 10, label: "Outubro/2026", reference_year: 2026, reference_month: 10, start_date: "2026-10-01", end_date: "2026-10-31", status: "open" },
    { id: 9, label: "Setembro/2026", reference_year: 2026, reference_month: 9, start_date: "2026-09-01", end_date: "2026-09-30", status: "open" },
    { id: 8, label: "Agosto/2026", reference_year: 2026, reference_month: 8, start_date: "2026-08-01", end_date: "2026-08-31", status: "open" },
    { id: 7, label: "Julho/2026", reference_year: 2026, reference_month: 7, start_date: "2026-07-01", end_date: "2026-07-31", status: "closed" },
  ],
  reportingPeriodPolicy: {
    minDate: "2024-08-01",
    maxDate: "2026-11-01",
  },
  catalog: {
    modules: [
      {
        id: 1,
        code: "clinical_screening",
        name: "Triagem clínica",
        description: "Instrumento demonstrativo de triagem e captação com dados-base agregados.",
        display_order: 1,
        active: true,
        version: 1,
        valid_from: "2026-08-11",
        valid_to: null,
        is_demo: true,
        status: "demonstrativo",
      },
      {
        id: 2,
        code: "collection_operations",
        name: "Coleta",
        description: "Base operacional agregada da sessão de coleta.",
        display_order: 2,
        active: true,
        version: 1,
        valid_from: "2026-08-11",
        valid_to: null,
        is_demo: true,
        status: "demonstrativo",
      },
      {
        id: 3,
        code: "laboratory_screening",
        name: "Exames realizados",
        description: "Estrutura demonstrativa para totais laboratoriais e registro agregado por exame.",
        display_order: 3,
        active: true,
        version: 1,
        valid_from: "2026-08-11",
        valid_to: null,
        is_demo: true,
        status: "candidato",
      },
      {
        id: 4,
        code: "hemotherapy_production",
        name: "Produção hemoterápica",
        description: "Estrutura tabular demonstrativa por hemocomponente.",
        display_order: 4,
        active: true,
        version: 1,
        valid_from: "2026-08-11",
        valid_to: null,
        is_demo: true,
        status: "candidato",
      },
      {
        id: 5,
        code: "transfusion_distribution",
        name: "Transfusão / distribuição",
        description: "Base agregada demonstrativa para transfusão e distribuição.",
        display_order: 5,
        active: true,
        version: 1,
        valid_from: "2026-08-11",
        valid_to: null,
        is_demo: true,
        status: "candidato",
      },
    ],
    variables: [
      variable(1, "donacoes_voluntarias", "Doações voluntárias/espontâneas", 1, "clinical_screening", "doações", true, 1, "Indicador principal.", { section_code: "tipo_doacao", section_name: "Tipo de doação", section_description: "Composição das doações do período.", section_layout: "fields" }),
      variable(2, "donacoes_reposicao", "Doações de reposição", 1, "clinical_screening", "doações", true, 2, "Indicador principal.", { section_code: "tipo_doacao", section_name: "Tipo de doação", section_description: "Composição das doações do período.", section_layout: "fields" }),
      variable(3, "candidatos_aptos", "Candidatos aptos", 1, "clinical_screening", "candidatos", true, 3, "Indicador principal.", { section_code: "aptidao", section_name: "Resultado da triagem", section_description: "Base principal para cálculo da taxa de inaptidão clínica.", section_layout: "fields" }),
      variable(4, "candidatos_inaptos", "Candidatos inaptos", 1, "clinical_screening", "candidatos", true, 4, "Indicador principal.", { section_code: "aptidao", section_name: "Resultado da triagem", section_description: "Base principal para cálculo da taxa de inaptidão clínica.", section_layout: "fields" }),
      variable(5, "doador_primeira_vez", "Doadores de primeira vez", 1, "clinical_screening", "doadores", false, 5, "Estratificação demonstrativa.", { section_code: "tipo_doador", section_name: "Tipo de doador", section_description: "Estratificação agregada demonstrativa.", section_layout: "fields" }),
      variable(6, "doador_repeticao", "Doadores de repetição", 1, "clinical_screening", "doadores", false, 6, "Estratificação demonstrativa.", { section_code: "tipo_doador", section_name: "Tipo de doador", section_description: "Estratificação agregada demonstrativa.", section_layout: "fields" }),
      variable(7, "triagem_feminino", "Sexo feminino", 1, "clinical_screening", "candidatos", false, 7, "Corte demonstrativo.", { section_code: "sexo", section_name: "Sexo", section_description: "Distribuição agregada por sexo.", section_layout: "fields" }),
      variable(8, "triagem_masculino", "Sexo masculino", 1, "clinical_screening", "candidatos", false, 8, "Corte demonstrativo.", { section_code: "sexo", section_name: "Sexo", section_description: "Distribuição agregada por sexo.", section_layout: "fields" }),
      variable(9, "inaptidao_anemia", "Inaptidão por anemia", 1, "clinical_screening", "ocorrências", false, 9, "Catálogo candidato.", { section_code: "causas_inaptidao", section_name: "Causas de inaptidão", section_description: "Catálogo configurável e demonstrativo.", section_layout: "fields" }),
      variable(10, "inaptidao_outros", "Inaptidão por outros motivos", 1, "clinical_screening", "ocorrências", false, 10, "Catálogo candidato.", { section_code: "causas_inaptidao", section_name: "Causas de inaptidão", section_description: "Catálogo configurável e demonstrativo.", section_layout: "fields" }),
      variable(40, "candidatos_convocados", "Candidatos convocados", 1, "clinical_screening", "candidatos", false, 11, "Base demonstrativa para taxa de comparecimento.", { section_code: "comparecimento", section_name: "Convocação e comparecimento", section_description: "Dados-base demonstrativos para leitura de comparecimento.", section_layout: "fields", status: "demonstrativo" }),
      variable(41, "candidatos_compareceram", "Candidatos que compareceram", 1, "clinical_screening", "candidatos", false, 12, "Base demonstrativa para taxa de comparecimento.", { section_code: "comparecimento", section_name: "Convocação e comparecimento", section_description: "Dados-base demonstrativos para leitura de comparecimento.", section_layout: "fields", status: "demonstrativo" }),
      variable(11, "candidatos_desistentes", "Candidatos desistentes", 2, "collection_operations", "candidatos", false, 1, "Perda operacional.", { section_code: "interrupcoes", section_name: "Interrupções e desistências", section_description: "Eventos agregados que podem interromper a coleta.", section_layout: "fields" }),
      variable(12, "dificuldade_puncao_venosa", "Dificuldade de punção venosa", 2, "collection_operations", "ocorrências", false, 2, "Perda operacional.", { section_code: "interrupcoes", section_name: "Interrupções e desistências", section_description: "Eventos agregados que podem interromper a coleta.", section_layout: "fields" }),
      variable(13, "reacao_vagal", "Reação vagal", 2, "collection_operations", "ocorrências", false, 3, "Perda operacional.", { section_code: "interrupcoes", section_name: "Interrupções e desistências", section_description: "Eventos agregados que podem interromper a coleta.", section_layout: "fields" }),
      variable(14, "interrupcao_outros_motivos", "Outros motivos de interrupção", 2, "collection_operations", "ocorrências", false, 4, "Perda operacional.", { section_code: "interrupcoes", section_name: "Interrupções e desistências", section_description: "Eventos agregados que podem interromper a coleta.", section_layout: "fields" }),
      variable(15, "coletas_sangue_total", "Coletas de sangue total", 2, "collection_operations", "coletas", false, 5, "Volume operacional.", { section_code: "modalidade", section_name: "Modalidade da coleta", section_description: "Distribuição agregada das coletas concluídas.", section_layout: "fields" }),
      variable(16, "coletas_aferese", "Coletas por aférese", 2, "collection_operations", "coletas", false, 6, "Volume operacional.", { section_code: "modalidade", section_name: "Modalidade da coleta", section_description: "Distribuição agregada das coletas concluídas.", section_layout: "fields" }),
      variable(17, "amostras_testadas", "Amostras/bolsas testadas", 3, "laboratory_screening", "amostras/bolsas", false, 1, "Indicador principal.", { section_code: "totais_exames", section_name: "Totais consolidados dos exames", section_description: "Campos derivados somente leitura para manter o sync atual.", section_layout: "fields", read_only: true, derived_value_operation: "sum", derived_value_sources: ["exame_sifilis_testadas", "exame_hiv_testadas", "exame_hbv_testadas", "exame_hcv_testadas", "exame_malaria_testadas", "exame_outros_testadas"] }),
      variable(18, "amostras_reagentes", "Amostras/bolsas reagentes para um ou mais marcadores", 3, "laboratory_screening", "amostras/bolsas", false, 2, "Indicador principal.", { section_code: "totais_exames", section_name: "Totais consolidados dos exames", section_description: "Campos derivados somente leitura para manter o sync atual.", section_layout: "fields", read_only: true, derived_value_operation: "sum", derived_value_sources: ["exame_sifilis_reagentes", "exame_hiv_reagentes", "exame_hbv_reagentes", "exame_hcv_reagentes", "exame_malaria_reagentes", "exame_outros_reagentes"] }),
      variable(19, "exame_sifilis_testadas", "Sífilis: amostras testadas", 3, "laboratory_screening", "amostras", false, 3, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "sifilis", matrix_row_label: "Sífilis", matrix_row_order: 1, matrix_column_code: "testadas", matrix_column_label: "Amostras testadas", matrix_column_order: 1 }),
      variable(20, "exame_sifilis_reagentes", "Sífilis: amostras reagentes", 3, "laboratory_screening", "amostras", false, 4, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "sifilis", matrix_row_label: "Sífilis", matrix_row_order: 1, matrix_column_code: "reagentes", matrix_column_label: "Amostras reagentes", matrix_column_order: 2 }),
      variable(21, "exame_hiv_testadas", "HIV: amostras testadas", 3, "laboratory_screening", "amostras", false, 5, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "hiv", matrix_row_label: "HIV", matrix_row_order: 2, matrix_column_code: "testadas", matrix_column_label: "Amostras testadas", matrix_column_order: 1 }),
      variable(22, "exame_hiv_reagentes", "HIV: amostras reagentes", 3, "laboratory_screening", "amostras", false, 6, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "hiv", matrix_row_label: "HIV", matrix_row_order: 2, matrix_column_code: "reagentes", matrix_column_label: "Amostras reagentes", matrix_column_order: 2 }),
      variable(23, "exame_hbv_testadas", "Hepatite B: amostras testadas", 3, "laboratory_screening", "amostras", false, 7, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "hbv", matrix_row_label: "Hepatite B", matrix_row_order: 3, matrix_column_code: "testadas", matrix_column_label: "Amostras testadas", matrix_column_order: 1 }),
      variable(24, "exame_hbv_reagentes", "Hepatite B: amostras reagentes", 3, "laboratory_screening", "amostras", false, 8, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "hbv", matrix_row_label: "Hepatite B", matrix_row_order: 3, matrix_column_code: "reagentes", matrix_column_label: "Amostras reagentes", matrix_column_order: 2 }),
      variable(42, "exame_hcv_testadas", "Hepatite C: amostras testadas", 3, "laboratory_screening", "amostras", false, 9, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "hcv", matrix_row_label: "Hepatite C", matrix_row_order: 4, matrix_column_code: "testadas", matrix_column_label: "Amostras testadas", matrix_column_order: 1, status: "candidato" }),
      variable(43, "exame_hcv_reagentes", "Hepatite C: amostras reagentes", 3, "laboratory_screening", "amostras", false, 10, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "hcv", matrix_row_label: "Hepatite C", matrix_row_order: 4, matrix_column_code: "reagentes", matrix_column_label: "Amostras reagentes", matrix_column_order: 2, status: "candidato" }),
      variable(44, "exame_malaria_testadas", "Malária: amostras testadas", 3, "laboratory_screening", "amostras", false, 11, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "malaria", matrix_row_label: "Malária", matrix_row_order: 5, matrix_column_code: "testadas", matrix_column_label: "Amostras testadas", matrix_column_order: 1, status: "candidato" }),
      variable(45, "exame_malaria_reagentes", "Malária: amostras reagentes", 3, "laboratory_screening", "amostras", false, 12, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "malaria", matrix_row_label: "Malária", matrix_row_order: 5, matrix_column_code: "reagentes", matrix_column_label: "Amostras reagentes", matrix_column_order: 2, status: "candidato" }),
      variable(46, "exame_outros_testadas", "Outros marcadores: amostras testadas", 3, "laboratory_screening", "amostras", false, 13, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "outros", matrix_row_label: "Outros", matrix_row_order: 6, matrix_column_code: "testadas", matrix_column_label: "Amostras testadas", matrix_column_order: 1, status: "candidato" }),
      variable(47, "exame_outros_reagentes", "Outros marcadores: amostras reagentes", 3, "laboratory_screening", "amostras", false, 14, "Configuração demonstrativa.", { section_code: "exames", section_name: "Exames realizados", section_description: "Tabela demonstrativa por exame.", section_layout: "matrix", matrix_code: "serologia", matrix_name: "Serologia agregada", matrix_description: "Informe testadas e reagentes por exame.", matrix_row_code: "outros", matrix_row_label: "Outros", matrix_row_order: 6, matrix_column_code: "reagentes", matrix_column_label: "Amostras reagentes", matrix_column_order: 2, status: "candidato" }),
      variable(25, "producao_hemacias_produzidas", "Concentrado de hemácias produzidas", 4, "hemotherapy_production", "hemocomponentes", false, 1, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "hemacias", matrix_row_label: "Concentrado de hemácias", matrix_row_order: 1, matrix_column_code: "produzidas", matrix_column_label: "Produzidas", matrix_column_order: 1 }),
      variable(26, "producao_hemacias_recebidas", "Concentrado de hemácias recebidas", 4, "hemotherapy_production", "hemocomponentes", false, 2, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "hemacias", matrix_row_label: "Concentrado de hemácias", matrix_row_order: 1, matrix_column_code: "recebidas", matrix_column_label: "Recebidas", matrix_column_order: 2 }),
      variable(27, "producao_hemacias_devolvidas", "Concentrado de hemácias devolvidas", 4, "hemotherapy_production", "hemocomponentes", false, 3, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "hemacias", matrix_row_label: "Concentrado de hemácias", matrix_row_order: 1, matrix_column_code: "devolvidas", matrix_column_label: "Devolvidas", matrix_column_order: 3 }),
      variable(28, "producao_plaquetas_produzidas", "Concentrado de plaquetas produzidas", 4, "hemotherapy_production", "hemocomponentes", false, 4, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "plaquetas", matrix_row_label: "Concentrado de plaquetas", matrix_row_order: 2, matrix_column_code: "produzidas", matrix_column_label: "Produzidas", matrix_column_order: 1 }),
      variable(29, "producao_plaquetas_recebidas", "Concentrado de plaquetas recebidas", 4, "hemotherapy_production", "hemocomponentes", false, 5, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "plaquetas", matrix_row_label: "Concentrado de plaquetas", matrix_row_order: 2, matrix_column_code: "recebidas", matrix_column_label: "Recebidas", matrix_column_order: 2 }),
      variable(30, "producao_plaquetas_devolvidas", "Concentrado de plaquetas devolvidas", 4, "hemotherapy_production", "hemocomponentes", false, 6, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "plaquetas", matrix_row_label: "Concentrado de plaquetas", matrix_row_order: 2, matrix_column_code: "devolvidas", matrix_column_label: "Devolvidas", matrix_column_order: 3 }),
      variable(31, "producao_plasma_produzidas", "Plasma produzido", 4, "hemotherapy_production", "hemocomponentes", false, 7, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "plasma", matrix_row_label: "Plasma", matrix_row_order: 3, matrix_column_code: "produzidas", matrix_column_label: "Produzidas", matrix_column_order: 1 }),
      variable(32, "producao_plasma_recebidas", "Plasma recebido", 4, "hemotherapy_production", "hemocomponentes", false, 8, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "plasma", matrix_row_label: "Plasma", matrix_row_order: 3, matrix_column_code: "recebidas", matrix_column_label: "Recebidas", matrix_column_order: 2 }),
      variable(33, "producao_plasma_devolvidas", "Plasma devolvido", 4, "hemotherapy_production", "hemocomponentes", false, 9, "Estrutura candidata.", { section_code: "producao", section_name: "Produção por hemocomponente", section_description: "Matriz demonstrativa de volumes por hemocomponente.", section_layout: "matrix", matrix_code: "producao", matrix_name: "Produção hemoterápica", matrix_description: "Volumes produzidos, recebidos e devolvidos.", matrix_row_code: "plasma", matrix_row_label: "Plasma", matrix_row_order: 3, matrix_column_code: "devolvidas", matrix_column_label: "Devolvidas", matrix_column_order: 3 }),
      variable(34, "transfusao_hemacias_ambulatorial", "Transfusão ambulatorial de hemácias", 5, "transfusion_distribution", "hemocomponentes", false, 1, "Estrutura candidata.", { section_code: "transfusao", section_name: "Transfusão por canal", section_description: "Volumes agregados por hemocomponente e canal.", section_layout: "matrix", matrix_code: "transfusao", matrix_name: "Transfusão / distribuição", matrix_description: "Volumes agregados por hemocomponente.", matrix_row_code: "hemacias", matrix_row_label: "Hemácias", matrix_row_order: 1, matrix_column_code: "ambulatorial", matrix_column_label: "Ambulatorial", matrix_column_order: 1 }),
      variable(35, "transfusao_hemacias_hospitalar", "Transfusão hospitalar de hemácias", 5, "transfusion_distribution", "hemocomponentes", false, 2, "Estrutura candidata.", { section_code: "transfusao", section_name: "Transfusão por canal", section_description: "Volumes agregados por hemocomponente e canal.", section_layout: "matrix", matrix_code: "transfusao", matrix_name: "Transfusão / distribuição", matrix_description: "Volumes agregados por hemocomponente.", matrix_row_code: "hemacias", matrix_row_label: "Hemácias", matrix_row_order: 1, matrix_column_code: "hospitalar", matrix_column_label: "Hospitalar", matrix_column_order: 2 }),
      variable(36, "transfusao_plaquetas_ambulatorial", "Transfusão ambulatorial de plaquetas", 5, "transfusion_distribution", "hemocomponentes", false, 3, "Estrutura candidata.", { section_code: "transfusao", section_name: "Transfusão por canal", section_description: "Volumes agregados por hemocomponente e canal.", section_layout: "matrix", matrix_code: "transfusao", matrix_name: "Transfusão / distribuição", matrix_description: "Volumes agregados por hemocomponente.", matrix_row_code: "plaquetas", matrix_row_label: "Plaquetas", matrix_row_order: 2, matrix_column_code: "ambulatorial", matrix_column_label: "Ambulatorial", matrix_column_order: 1 }),
      variable(37, "transfusao_plaquetas_hospitalar", "Transfusão hospitalar de plaquetas", 5, "transfusion_distribution", "hemocomponentes", false, 4, "Estrutura candidata.", { section_code: "transfusao", section_name: "Transfusão por canal", section_description: "Volumes agregados por hemocomponente e canal.", section_layout: "matrix", matrix_code: "transfusao", matrix_name: "Transfusão / distribuição", matrix_description: "Volumes agregados por hemocomponente.", matrix_row_code: "plaquetas", matrix_row_label: "Plaquetas", matrix_row_order: 2, matrix_column_code: "hospitalar", matrix_column_label: "Hospitalar", matrix_column_order: 2 }),
      variable(38, "distribuicao_com_exame_pre_transfusional", "Distribuição com exame pré-transfusional", 5, "transfusion_distribution", "distribuições", false, 5, "Estrutura candidata.", { section_code: "distribuicao", section_name: "Distribuição", section_description: "Estrutura demonstrativa adicional para distribuição.", section_layout: "fields" }),
      variable(39, "distribuicao_sem_exame_pre_transfusional", "Distribuição sem exame pré-transfusional", 5, "transfusion_distribution", "distribuições", false, 6, "Estrutura candidata.", { section_code: "distribuicao", section_name: "Distribuição", section_description: "Estrutura demonstrativa adicional para distribuição.", section_layout: "fields" }),
    ],
    indicators: [
      indicator(
        1,
        "percentual_doacoes_voluntarias",
        "Percentual de doações voluntárias",
        1,
        "clinical_screening",
        "share_of_sum_percentage",
        "doações voluntárias ÷ (doações voluntárias + doações de reposição) × 100",
        1,
        "donacoes_voluntarias",
        2,
        "donacoes_reposicao",
      ),
      indicator(
        2,
        "taxa_inaptidao_clinica",
        "Taxa de inaptidão clínica",
        1,
        "clinical_screening",
        "share_of_sum_percentage",
        "candidatos inaptos ÷ (candidatos aptos + candidatos inaptos) × 100",
        4,
        "candidatos_inaptos",
        3,
        "candidatos_aptos",
      ),
      indicator(
        3,
        "taxa_reatividade",
        "Taxa de reatividade",
        3,
        "laboratory_screening",
        "ratio_percentage",
        "amostras reagentes ÷ amostras testadas × 100",
        18,
        "amostras_reagentes",
        17,
        "amostras_testadas",
      ),
      indicator(
        4,
        "taxa_comparecimento",
        "Taxa de comparecimento",
        1,
        "clinical_screening",
        "ratio_percentage",
        "candidatos que compareceram ÷ candidatos convocados × 100",
        41,
        "candidatos_compareceram",
        40,
        "candidatos_convocados",
      ),
      indicator(
        5,
        "taxa_reatividade_hiv",
        "Taxa de reatividade por marcador: HIV",
        3,
        "laboratory_screening",
        "ratio_percentage",
        "amostras reagentes para HIV ÷ amostras testadas para HIV × 100",
        22,
        "exame_hiv_reagentes",
        21,
        "exame_hiv_testadas",
      ),
      indicator(
        6,
        "taxa_reatividade_hbv",
        "Taxa de reatividade por marcador: Hepatite B",
        3,
        "laboratory_screening",
        "ratio_percentage",
        "amostras reagentes para hepatite B ÷ amostras testadas para hepatite B × 100",
        24,
        "exame_hbv_reagentes",
        23,
        "exame_hbv_testadas",
      ),
      indicator(
        7,
        "taxa_reatividade_sifilis",
        "Taxa de reatividade por marcador: Sífilis",
        3,
        "laboratory_screening",
        "ratio_percentage",
        "amostras reagentes para sífilis ÷ amostras testadas para sífilis × 100",
        20,
        "exame_sifilis_reagentes",
        19,
        "exame_sifilis_testadas",
      ),
    ],
  },
  user: {
    username: "operador",
    fullName: "Operador Demo",
    role: "operator",
    displayRole: "Operador",
  },
  demoNotice:
    "Configuração demonstrativa. Os indicadores definitivos serão priorizados e validados em conjunto com o Instituto Nacional de Sangue.",
};
