import type { BootstrapPayload } from "../types/submission";


export const demoBootstrap: BootstrapPayload = {
  institution: { id: 1, name: "Instituição Demonstrativa" },
  unit: { id: 1, name: "Unidade Demonstrativa", code: "DEMO" },
  reportingPeriod: {
    id: 8,
    label: "Agosto/2026",
    reference_year: 2026,
    reference_month: 8,
    start_date: "2026-08-01",
    end_date: "2026-08-31",
    status: "open",
  },
  reportingPeriods: [
    { id: 12, label: "Dezembro/2026", reference_year: 2026, reference_month: 12, start_date: "2026-12-01", end_date: "2026-12-31", status: "open" },
    { id: 11, label: "Novembro/2026", reference_year: 2026, reference_month: 11, start_date: "2026-11-01", end_date: "2026-11-30", status: "open" },
    { id: 10, label: "Outubro/2026", reference_year: 2026, reference_month: 10, start_date: "2026-10-01", end_date: "2026-10-31", status: "open" },
    { id: 9, label: "Setembro/2026", reference_year: 2026, reference_month: 9, start_date: "2026-09-01", end_date: "2026-09-30", status: "open" },
    { id: 8, label: "Agosto/2026", reference_year: 2026, reference_month: 8, start_date: "2026-08-01", end_date: "2026-08-31", status: "open" },
    { id: 7, label: "Julho/2026", reference_year: 2026, reference_month: 7, start_date: "2026-07-01", end_date: "2026-07-31", status: "closed" },
    { id: 6, label: "Junho/2026", reference_year: 2026, reference_month: 6, start_date: "2026-06-01", end_date: "2026-06-30", status: "closed" },
    { id: 5, label: "Maio/2026", reference_year: 2026, reference_month: 5, start_date: "2026-05-01", end_date: "2026-05-31", status: "closed" },
    { id: 4, label: "Abril/2026", reference_year: 2026, reference_month: 4, start_date: "2026-04-01", end_date: "2026-04-30", status: "closed" },
    { id: 3, label: "Marco/2026", reference_year: 2026, reference_month: 3, start_date: "2026-03-01", end_date: "2026-03-31", status: "closed" },
    { id: 2, label: "Fevereiro/2026", reference_year: 2026, reference_month: 2, start_date: "2026-02-01", end_date: "2026-02-28", status: "closed" },
    { id: 1, label: "Janeiro/2026", reference_year: 2026, reference_month: 1, start_date: "2026-01-01", end_date: "2026-01-31", status: "closed" },
  ],
  reportingPeriodPolicy: {
    minDate: "2024-08-01",
    maxDate: "2026-11-01",
  },
  catalog: {
    modules: [
      {
        id: 1,
        code: "donation_capture",
        name: "Doação e captação",
        description: "Informe apenas totais agregados do período para doações voluntárias e de reposição.",
        display_order: 1,
        active: true,
        version: 1,
        valid_from: "2026-08-01",
        valid_to: null,
        is_demo: true,
      },
      {
        id: 2,
        code: "clinical_screening",
        name: "Triagem clínica",
        description: "Registre os totais agregados de candidatos aptos e inaptos na triagem clínica do período.",
        display_order: 2,
        active: true,
        version: 1,
        valid_from: "2026-08-01",
        valid_to: null,
        is_demo: true,
      },
      {
        id: 3,
        code: "laboratory_screening",
        name: "Triagem laboratorial",
        description: "Registre o total agregado de amostras ou bolsas testadas e o total reagente para um ou mais marcadores.",
        display_order: 3,
        active: true,
        version: 1,
        valid_from: "2026-08-01",
        valid_to: null,
        is_demo: true,
      },
    ],
    variables: [
      {
        id: 1,
        code: "donacoes_voluntarias",
        name: "Doações voluntárias/espontâneas",
        operational_definition: "Quantidade agregada de doações voluntárias ou espontâneas registradas na unidade no período.",
        module: 1,
        module_code: "donation_capture",
        variable_type: "integer",
        unit: "doações",
        required: true,
        min_value: 0,
        max_value: null,
        expected_source: "Registro institucional da unidade.",
        help_text: "Use apenas dados institucionais agregados; não informe dados individuais.",
        display_order: 1,
        active: true,
        version: 1,
        select_options: [],
        is_demo: true,
      },
      {
        id: 2,
        code: "donacoes_reposicao",
        name: "Doações de reposição",
        operational_definition: "Quantidade agregada de doações de reposição registradas na unidade no período.",
        module: 1,
        module_code: "donation_capture",
        variable_type: "integer",
        unit: "doações",
        required: true,
        min_value: 0,
        max_value: null,
        expected_source: "Registro institucional da unidade.",
        help_text: "Use apenas dados institucionais agregados; não informe dados individuais.",
        display_order: 2,
        active: true,
        version: 1,
        select_options: [],
        is_demo: true,
      },
      {
        id: 3,
        code: "candidatos_aptos",
        name: "Candidatos aptos",
        operational_definition: "Quantidade agregada de candidatos considerados aptos na triagem clínica do período.",
        module: 2,
        module_code: "clinical_screening",
        variable_type: "integer",
        unit: "candidatos",
        required: true,
        min_value: 0,
        max_value: null,
        expected_source: "Registro de triagem clínica da unidade.",
        help_text: "Use apenas dados institucionais agregados; não informe dados individuais.",
        display_order: 1,
        active: true,
        version: 1,
        select_options: [],
        is_demo: true,
      },
      {
        id: 4,
        code: "candidatos_inaptos",
        name: "Candidatos inaptos",
        operational_definition: "Quantidade agregada de candidatos considerados inaptos na triagem clínica do período.",
        module: 2,
        module_code: "clinical_screening",
        variable_type: "integer",
        unit: "candidatos",
        required: true,
        min_value: 0,
        max_value: null,
        expected_source: "Registro de triagem clínica da unidade.",
        help_text: "Use apenas dados institucionais agregados; não informe dados individuais.",
        display_order: 2,
        active: true,
        version: 1,
        select_options: [],
        is_demo: true,
      },
      {
        id: 5,
        code: "amostras_testadas",
        name: "Amostras/bolsas testadas",
        operational_definition: "Quantidade agregada de amostras ou bolsas testadas na triagem laboratorial no período.",
        module: 3,
        module_code: "laboratory_screening",
        variable_type: "integer",
        unit: "amostras/bolsas",
        required: true,
        min_value: 0,
        max_value: null,
        expected_source: "Registro laboratorial da unidade.",
        help_text: "Use apenas totais agregados do período.",
        display_order: 1,
        active: true,
        version: 1,
        select_options: [],
        is_demo: true,
      },
      {
        id: 6,
        code: "amostras_reagentes",
        name: "Amostras/bolsas reagentes para um ou mais marcadores",
        operational_definition: "Quantidade agregada de amostras ou bolsas reagentes para um ou mais marcadores na triagem laboratorial do período.",
        module: 3,
        module_code: "laboratory_screening",
        variable_type: "integer",
        unit: "amostras/bolsas",
        required: true,
        min_value: 0,
        max_value: null,
        expected_source: "Registro laboratorial da unidade.",
        help_text: "Use apenas totais agregados do período.",
        display_order: 2,
        active: true,
        version: 1,
        select_options: [],
        is_demo: true,
      },
    ],
    indicators: [
      {
        id: 1,
        code: "percentual_doacoes_voluntarias",
        name: "Percentual de doações voluntárias",
        definition: "Percentual de doações voluntárias em relação ao total calculado de doações voluntárias e de reposição do período.",
        module: 1,
        module_code: "donation_capture",
        dimension: "process",
        unit: "%",
        formula_kind: "share_of_sum_percentage",
        formula_label: "doações voluntárias ÷ (doações voluntárias + doações de reposição) × 100",
        numerator_variable: 1,
        numerator_variable_code: "donacoes_voluntarias",
        denominator_variable: 2,
        denominator_variable_code: "donacoes_reposicao",
        version: 1,
        valid_from: "2026-08-01",
        valid_to: null,
        interpretation: "Valores mais altos indicam maior participação de doações voluntárias no período.",
        is_demo: true,
      },
      {
        id: 2,
        code: "taxa_inaptidao_clinica",
        name: "Taxa de inaptidão clínica",
        definition: "Percentual de candidatos inaptos em relação ao total calculado de candidatos aptos e inaptos do período.",
        module: 2,
        module_code: "clinical_screening",
        dimension: "result",
        unit: "%",
        formula_kind: "share_of_sum_percentage",
        formula_label: "candidatos inaptos ÷ (candidatos aptos + candidatos inaptos) × 100",
        numerator_variable: 4,
        numerator_variable_code: "candidatos_inaptos",
        denominator_variable: 3,
        denominator_variable_code: "candidatos_aptos",
        version: 1,
        valid_from: "2026-08-01",
        valid_to: null,
        interpretation: "Valores mais altos indicam maior proporção de inaptidão clínica entre os candidatos triados.",
        is_demo: true,
      },
      {
        id: 3,
        code: "taxa_reatividade",
        name: "Taxa de reatividade",
        definition: "Percentual de amostras ou bolsas reagentes em relação ao total de amostras ou bolsas testadas no período.",
        module: 3,
        module_code: "laboratory_screening",
        dimension: "result",
        unit: "%",
        formula_kind: "ratio_percentage",
        formula_label: "amostras reagentes ÷ amostras testadas × 100",
        numerator_variable: 6,
        numerator_variable_code: "amostras_reagentes",
        denominator_variable: 5,
        denominator_variable_code: "amostras_testadas",
        version: 1,
        valid_from: "2026-08-01",
        valid_to: null,
        interpretation: "Valores mais altos indicam maior proporção de reatividade no conjunto laboratorial testado.",
        is_demo: true,
      },
    ],
  },
  user: { username: "operador", fullName: "Operador Demo", role: "operator" },
  demoNotice:
    "Configuração demonstrativa. Os indicadores definitivos serão priorizados e validados em conjunto com o Instituto Nacional de Sangue.",
};
